import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "LOL-DEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between items-center p-4 bg-gray-800 text-white">
          <nav className="flex gap-10">
            <Link href="/" className="hover:text-gray-300 transition">
              홈
            </Link>
            <Link href="/champions" className="hover:text-gray-300 transition">
              챔피언 목록
            </Link>
            <Link href="/items" className="hover:text-gray-300 transition">
              아이템 목록
            </Link>
            <Link href="/rotation" className="hover:text-gray-300 transition">
              챔피언 로테이션
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
